# Generated by Django 6.1 on 2026-08-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('translate', 'Translate'), ('word_bank', 'Word Bank'), ('match_pairs', 'Match Pairs'), ('fill_blank', 'Fill in the Blank'), ('type_answer', 'Type Answer')], max_length=30)),
                ('question', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('correct_answer', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('skill', 'order'), name='unique_lesson_order_per_skill'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_exercise_order_per_lesson'),
        ),
    ]
